/**
 * Calendar list consts
 */
export const CALENDAR_DATES_REQUESTED    = 'twoj_sklep/service/CALENDAR_DATES_REQUESTED'
export const CALENDAR_DATES_SUCCEEDED    = 'twoj_sklep/service/CALENDAR_DATES_SUCCEEDED'
export const CALENDAR_DATES_FAILED       = 'twoj_sklep/service/CALENDAR_DATES_FAILED'
export const CALENDAR_BOOK_REQUESTED    = 'twoj_sklep/service/CALENDAR_BOOK_REQUESTED'
export const CALENDAR_BOOK_SUCCEEDED    = 'twoj_sklep/service/CALENDAR_BOOK_SUCCEEDED'
export const CALENDAR_BOOK_FAILED       = 'twoj_sklep/service/CALENDAR_BOOK_FAILED'
export const CALENDAR_ORDER_REQUESTED    = 'twoj_sklep/service/CALENDAR_ORDER_REQUESTED'
export const CALENDAR_ORDER_SUCCEEDED    = 'twoj_sklep/service/CALENDAR_ORDER_SUCCEEDED'
export const CALENDAR_ORDER_FAILED       = 'twoj_sklep/service/CALENDAR_ORDER_FAILED'
export const CALENDAR_CLEAR       = 'twoj_sklep/service/CALENDAR_CLEAR'

export default {
    CALENDAR_DATES_REQUESTED, CALENDAR_DATES_SUCCEEDED, CALENDAR_DATES_FAILED,
    CALENDAR_BOOK_REQUESTED, CALENDAR_BOOK_SUCCEEDED, CALENDAR_BOOK_FAILED,
    CALENDAR_ORDER_REQUESTED, CALENDAR_ORDER_SUCCEEDED, CALENDAR_ORDER_FAILED,
    CALENDAR_CLEAR
}